### PR TITLE
Restore WebDAV support.

### PR DESCRIPTION
**Pull request by frapell**

### CODE REVIEW

**Review by ale-rt — APPROVED** [review]
Thanks! This LGTM.
I restarted the Plone 5.2 - Py2.7 job because the failing test looked unrelated to me.

**Review by ale-rt — CHANGES_REQUESTED** [review]
Ops! I notice that the towncrier extension is `fixed` while it should `bugfix`!

**Comment by frapell** [comment]
> Ops! I notice that the towncrier extension is `fixed` while it should `bugfix`!

Fixed! :)

**Comment by frapell** [comment]
@jenkins-plone-org please run jobs

**Review by ale-rt — APPROVED** [review]

**Pull request merged**
