### PR TITLE
Update tests

### PR DESCRIPTION
**Pull request by gforcada**
Use standard best practices for the layers.

That and removing ZopeTestCase probably fixes its test isolation problems.

### CODE REVIEW

**Comment by gforcada** [comment]
Anyone up to review and merge? Jenkins says it's ok :-)

**Comment by thet** [comment]
@gforcada will do.

**Comment by thet** [comment]
@gforcada where is the jenkins test run? it's not linked in the merge info block...

**Comment by thet** [comment]
I added it: http://jenkins.plone.org/job/pull-request-5.0/1046/

**Comment by gforcada** [comment]
@thet the missing jenkins info was probably due to me adding a new commit (just for the changelog entry). If you look at the commits there's a green tick on the last to previous commit.

Let's wait for this new run and merge. I'm interested in seeing if this pull request fixes https://github.com/plone/buildout.coredev/pull/183

**Comment by thet** [comment]
If so, I'll re-run the Zope 4 PLIP job! :)

**Comment by gforcada** [comment]
@thet it's green :)

**Comment by thet** [comment]
you're going to rerun https://github.com/plone/buildout.coredev/pull/183 ?

**Comment by thet** [comment]
added the checkout also to buildout.coredev 5.1 branch

**Pull request merged**
